package Polinators_20.model;

public enum CropType {

    FIELD_RAPE, FIELD_SUNFLOWER, FIELD_BUCKWHEAT,FIELD_SCORPIONWEED, FIELD_SHAMROCK, FIELD_BORAGE, FIELD_HEATHER
    //RZEPAK,      SŁONECZNIK,        GRYKA,          FACELIA,        KONICZYNA,     OGÓRECZNIK,     WRZOS
}
